config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :equipment
  patch 'users_otp/enable'
  get 'users_otp/disable'
  devise_for :users, :path_prefix => "my", controllers: {
    sessions: 'sessions',
    registrations: 'users/registrations'
   }
   resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "equipment#index"
  # Defines the root path route ("/")
  # root "articles#index"
  post 'users/confirm_password_user/:id', to: 'users#confirm_password_user', as: 'confirm_password_user'
  post 'users/confirm_password_client/:id', to: 'users#confirm_password_client', as: 'confirm_password_client'
  post 'users/confirm_password_equipment/:id', to: 'users#confirm_password_equipment', as: 'confirm_password_equipment'
end

app/models/equipment.rb
class Equipment < ApplicationRecord

  enum status: ["Disponible", "Fuera de servicio", "En mantenimiento"]


    def self.search(search)
      if search
        where({name: search})
      else
        all
      end
    end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :authenticate_user!
  before_action :set_equipment, only: %i[ show edit update destroy ]

  # GET /equipment or /equipment.json
  def index
    if params[:search].present?
      search_term = "%#{params[:search]}%"
      query = "name LIKE :search OR status = :status"
      bindings = { search: search_term, status: Equipment.statuses[params[:search]] }

      if params[:search] == "Peso libre"
        query += " OR free_weigth = :free_weigth"
        bindings[:free_weigth] = true
      end

      @equipments = Equipment.where(query, bindings)
    else
      @equipments = Equipment.all
    end
  end

  # GET /equipment/1 or /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment or /equipment.json
  def create
    params = equipment_params
    params[:status]= params[:status].to_i
    if params[:current_password].present?
      if current_user.valid_password?(params[:current_password])
        params.delete(:current_password)
        @equipment = Equipment.new(params) 
        respond_to do |format|
          if @equipment.save
            format.html { redirect_to  equipment_index_path, notice: "Equipment was successfully created." }
            format.json { render :show, status: :created, location: @equipment }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @equipment.errors, status: :unprocessable_entity }
          end
        end
      else
        flash[:alert] = "Current password is incorrect"
        redirect_to new_equipment_path
      end
    else
      flash[:alert] = "Current password is required"
      redirect_to new_equipment_path
    end
  end

  # PATCH/PUT /equipment/1 or /equipment/1.json
  def update
    params = equipment_params
    params[:status]= params[:status].to_i
    if params[:current_password].present?
      if current_user.valid_password?(params[:current_password])
        params.delete(:current_password)
    respond_to do |format|
      if @equipment.update(params)
        format.html { redirect_to equipment_index_path, notice: "Equipment was successfully updated." }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
    else
      flash[:alert] = "Current password is incorrect"
      redirect_to equipment_index_path
    end
  else
    flash[:alert] = "Current password is required"
    redirect_to equipment_index_path
  end
end


  # DELETE /equipment/1 or /equipment/1.json
  def destroy
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: "Equipment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipment_params
      params.require(:equipment).permit(:free_weigth, :name, :status, :current_password)
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_equipment.html.erb
  <div id="<%= dom_id equipment %>">
    <p>
      <strong>Free weigth:</strong>
      <%= equipment.free_weigth %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= equipment.name %>
    </p>
  </div>

app/views/equipment/_form.html.erb
<div class="container">



<%= form_with(model: equipment, class: "form", data:{controller: "edit"}) do |form| %>
  <% if equipment.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
        <% equipment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%if current_user.admin?%>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :free_weigth, class: "form-label" %>
    <%= form.select :free_weigth, [["Peso libre", true], ["Maquina", false]], {}, class: "form-select" %>
  </div>
<%end%>
  <div class="mb-3">
    <%= form.label :status, class: "form-label" %>
    <%= form.select :status, [["Funcionando", 0], ["Fuera de servicio", 1], ["En reparacion", 2]], {}, class: "form-select" %>
  </div>
<%= form.label :current_password%>
    <%= form.password_field :current_password, id:"client_current_password" %>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary", id:"button_client" %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<div class="container">
  <div class="row mb-3">
      <div class="col-12">
        <h1>Editar aparato</h1>
      </div>
<%= render "form", equipment: @equipment %>

<br>

<div>
  <%= link_to "Regresar a aparatos", equipment_index_path %>
</div>

app/views/equipment/index.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-12">
      <h1>Aparatos</h1>
    </div>
  </div>
  <div class="row mb-3">
    <%if current_user.admin?%>
      <div class="col-6">
        <%= link_to "Agregar aparato", new_equipment_path, class: "btn btn-success" %>
      </div>
    <%end%>
    <div class="col-md-6 d-flex justify-content-end align-items-center">
      <%= form_tag(equipment_index_path, method: :get, class: "form-inline") do %>
        <div class="input-group">
          <%= text_field_tag(:search, params[:search], placeholder: "Buscar aparatos", class: "form-control", style: "width:auto") %>
          <div class="input-group-append">
            <%= submit_tag("Buscar", class: "btn btn-primary", style: "margin-left: 10px;") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Peso libre</th>
            <th>Estado</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @equipments.each do |equipment| %>
            <tr>
              <td><%= equipment.name %></td>
              <td><%= equipment.free_weigth ? "Peso libre" : "Aparato" %></td>
              <td><%= equipment.status%></td>
              <td>
                <%= link_to "Editar", edit_equipment_path(equipment), class: "btn btn-secondary" %>
                <%if current_user.admin?%>
                   <button onclick=<%="togglePasswordInput(#{equipment.id})"%>  class="btn btn-danger" id="delete-user-btn">
                Borrar
              </button>

                <div id=<%="password-input-#{equipment.id}"%> style="display: none;">
                   <%= form_tag confirm_password_equipment_path(equipment.id), data:{turbo: false, controller: "delete-equipment"},method: :post do %>
                      <%= label_tag :password, "Enter your password:" %>
                      <%= password_field_tag :password, nil, id: "password-#{equipment.id}", class: "form-control", data:{ delete_equipment_target:"password"} %>
                       <%= submit_tag "Confirm", class: "btn btn-primary", data:{ action: "click->delete-equipment#login"},id: "delete-equipment-#{equipment.id}" %>
                    <% end %>

            <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
   function togglePasswordInput(id) {
    let passwordInput = document.getElementById(`password-input-${id}`);
    if (passwordInput.style.display === "none") {
      passwordInput.style.display = "block";
    } else {
      passwordInput.style.display = "none";
    }
  }
</script>

app/views/equipment/new.html.erb
<div class="container">
  <div class="row mb-3">
      <div class="col-12">
        <h1>Nuevo aparato</h1>
      </div>
<%= render "form", equipment: @equipment %>

</div>

app/views/equipment/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @equipment %>

<div>
  <%= link_to "Edit this equipment", edit_equipment_path(@equipment) %> |
  <%= link_to "Back to equipment", equipment_index_path %>

  <%= button_to "Destroy this equipment", @equipment, method: :delete %>
</div>