config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :equipment
  patch 'users_otp/enable'
  get 'users_otp/disable'
  devise_for :users, :path_prefix => "my", controllers: {
    sessions: 'sessions',
    registrations: 'users/registrations'
   }
   resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "equipment#index"
  # Defines the root path route ("/")
  # root "articles#index"
  post 'users/confirm_password_user/:id', to: 'users#confirm_password_user', as: 'confirm_password_user'
  post 'users/confirm_password_client/:id', to: 'users#confirm_password_client', as: 'confirm_password_client'
  post 'users/confirm_password_equipment/:id', to: 'users#confirm_password_equipment', as: 'confirm_password_equipment'
end

app/models/client.rb
class Client < ApplicationRecord
    def age
        now = Time.now.utc.to_date
        now.year - self.birthdate.year - (self.birthdate.to_date.change(:year => now.year) > now ? 1 : 0)
      end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :admin_only, only: %i[ destroy ]
  # GET /clients or /clients.json
  def index
    if params[:search].present?
      search_term = "%#{params[:search]}%"
      @clients = Client.where("name LIKE ?", search_term)
    else
      @clients = Client.all
    end
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    params = client_params
    if params[:current_password].present?
      if current_user.valid_password?(params[:current_password])
        params.delete(:current_password)
        @client = Client.new(params)
        respond_to do |format|
          if @client.save
            format.html { redirect_to clients_path, notice: "Client was successfully created." }
            format.json { render :show, status: :created, location: @client }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @client.errors, status: :unprocessable_entity }
          end
        end
      else
        flash[:alert] = "Current password is incorrect"
        redirect_to :back
      end
    else
      flash[:alert] = "Current password is required"
      redirect_to :back
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    params = client_params
    if params[:current_password].present?
      if current_user.valid_password?(params[:current_password])
        params.delete(:current_password)
      respond_to do |format|
        if @client.update(params)
          format.html { redirect_to clients_path, notice: "Client was successfully updated." }
          format.json { render :show, status: :ok, location: @client }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @client.errors, status: :unprocessable_entity }
        end
      end
      else
        flash[:alert] = "Current password is incorrect"
        render :edit
      end
    else
      flash[:alert] = "Current password is required"
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :birthdate, :membership, :emergency_cname, :emergency_cphone, :current_password)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Name:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Birthdate:</strong>
    <%= client.birthdate %>
  </p>

  <p>
    <strong>Membership:</strong>
    <%= client.membership %>
  </p>

  <p>
    <strong>Emergency cname:</strong>
    <%= client.emergency_cname %>
  </p>

  <p>
    <strong>Emergency cphone:</strong>
    <%= client.emergency_cphone %>
  </p>

</div>

app/views/clients/_form.html.erb
<div class="container">
  <%= form_with(model: client, class: "form", data: { controller: "edit" }) do |form| %>
    <% if client.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>
        <ul>
          <% client.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
<%if current_user.admin? || current_page?(new_client_path)%>
    <div class="mb-3">
      <%= form.label :Nombre, class: "form-label", style: "display: block" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label "Fecha de nacimiento", class: "form-label", style: "display: block" %>
      <%= form.date_field :birthdate, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label "Contacto de emergencia", class: "form-label", style: "display: block" %>
      <%= form.text_field :emergency_cname, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :"Número de emergencia", class: "form-label", style: "display: block" %>
      <%= form.text_field :emergency_cphone, class: "form-control" %>
    </div>
<%end%>


<%if !current_page?(new_client_path)%>
 <div class="mb-3">
      <div class="form-check">
        <%= form.label "Membresía activa", class: "form-check-label" do %>
          <%= form.check_box :membership, class: "form-check-input" %>
          Activar membresia
        <% end %>
      </div>
    </div>
<%end%>
  <%= form.label :current_password %>
    <%= form.password_field :current_password %>

    <div class="mb-3">
      <%= form.submit "Guardar", class: "btn btn-primary", id: "button_client" %>
    </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<div class="container">
  <div class="row mb-3">
      <div class="col-12">
        <h1>Editar cliente</h1>
      </div>
<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Regresar a clientes", clients_path %>
</div>

app/views/clients/index.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col-12">
      <h1>Clientes</h1>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-md-6">
      <%= link_to "Agregar cliente", new_client_path, class: "btn btn-success" %>
    </div>
    <div class="col-md-6 d-flex justify-content-end align-items-center">
      <%= form_tag(clients_path, method: :get, class: "form-inline") do %>
        <div class="input-group">
          <%= text_field_tag(:search, params[:search], placeholder: "Buscar clientes", class: "form-control", style: "width:auto") %>
          <div class="input-group-append">
            <%= submit_tag("Buscar", class: "btn btn-primary", style: "margin-left: 10px;") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Edad</th>
        <th>Membresia</th>
        <th>Contacto de emergencia</th>
        <th>Teléfono de emergencia</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.name %></td>
          <td><%= client.age %></td>
          <td><%= client.membership ? "Activa" : "Inactiva" %></td>
          <td><%= client.emergency_cname %></td>
          <td><%= client.emergency_cphone %></td>
          <td>
            <%= link_to "Editar", edit_client_path(client), class: "btn btn-secondary" %>
            <% if current_user.admin? %>
              <button onclick=<%="togglePasswordInput(#{client.id})"%>  class="btn btn-danger" id="delete-user-btn">
                Borrar
              </button>

                <div id=<%="password-input-#{client.id}"%> style="display: none;">
                   <%= form_tag confirm_password_client_path(client.id), data:{controller: "delete-clients"},method: :post do %>
                      <%= label_tag :password, "Enter your password:" %>
                      <%= password_field_tag :password, nil, id: "current_psswd_clients", class: "form-control", data:{ delete_clients_target:"password"}%>
                      <%= submit_tag "Confirm", class: "btn btn-primary",data:{ action: "click->delete-clients#login"}, id: "delete-clients" %>
                    <% end %>

            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
   function togglePasswordInput(id) {
    let passwordInput = document.getElementById(`password-input-${id}`);
    if (passwordInput.style.display === "none") {
      passwordInput.style.display = "block";
    } else {
      passwordInput.style.display = "none";
    }
  }
</script>

app/views/clients/new.html.erb
<div class="container">
  <div class="row mb-3">
      <div class="col-12">
        <h1>Nuevo cliente</h1>
      </div>
<%= render "form", client: @client %>

</div>

<br>

<div>
  <%= link_to "Regresar a clientes", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>