config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :equipment
  patch 'users_otp/enable'
  get 'users_otp/disable'
  devise_for :users, :path_prefix => "my", controllers: {
    sessions: 'sessions',
    registrations: 'users/registrations'
   }
   resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "equipment#index"
  # Defines the root path route ("/")
  # root "articles#index"
  post 'users/confirm_password_user/:id', to: 'users#confirm_password_user', as: 'confirm_password_user'
  post 'users/confirm_password_client/:id', to: 'users#confirm_password_client', as: 'confirm_password_client'
  post 'users/confirm_password_equipment/:id', to: 'users#confirm_password_equipment', as: 'confirm_password_equipment'
end

app/controllers/users_otp_controller.rb
class UsersOtpController < ApplicationController
  before_action :authenticate_user!
  def enable
    current_user.otp_required_for_login = true
    current_user.otp_secret = User.generate_otp_secret
    current_user.save!
    redirect_back fallback_location: root_path
  end

  def disable
  end
  def two_fa
  end
end

app/helpers/users_otp_helper.rb
module UsersOtpHelper
end

app/views/users_otp/disable.html.erb
<h1>UsersOtp#disable</h1>
<p>Find me in app/views/users_otp/disable.html.erb</p>

app/views/users_otp/enable.html.erb
<h1>UsersOtp#enable</h1>
<p>Find me in app/views/users_otp/enable.html.erb</p>

app/views/users_otp/two_fa.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OTP Verification Form</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    body {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      background: linear-gradient(135deg, #FFE6E6, #AED6F1);
      background-size: cover;
    }
    
    .blur-background {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      backdrop-filter: blur(4px);
    }
    
    .logo-img {
      width: 120px;
      height: 120px;
      margin-bottom: 20px;
    }
    
    .container {
      max-width: 600px;
      background-color: rgba(255, 255, 255, 0.9);
      border-radius: 10px;
      padding: 40px;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    
    .form-group label {
      font-size: 20px;
      font-weight: bold;
    }
    
    .form-control {
      font-size: 18px;
      height: 50px;
    }
    
    .btn-primary {
      font-size: 20px;
      height: 50px;
      line-height: 1.5;
    }
  </style>
</head>
<body>
  <div class="blur-background"></div>
  <div class="container">
    <div class="card">
      <div class="card-body text-center">
        <%=image_tag "logo.png", alt:"Logo", class:"logo-img"%>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name), method: :post, html: { class: 'otp-form' }) do |f| %>
          <div class="form-group">
            <%= f.label :otp_attempt, class: 'form-label' %>
            <%= f.text_field :otp_attempt, class: 'form-control' %>
          </div>
          <%= f.submit "Enviar", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>