config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :equipment
  patch 'users_otp/enable'
  get 'users_otp/disable'
  devise_for :users, :path_prefix => "my", controllers: {
    sessions: 'sessions',
    registrations: 'users/registrations'
   }
   resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "equipment#index"
  # Defines the root path route ("/")
  # root "articles#index"
  post 'users/confirm_password_user/:id', to: 'users#confirm_password_user', as: 'confirm_password_user'
  post 'users/confirm_password_client/:id', to: 'users#confirm_password_client', as: 'confirm_password_client'
  post 'users/confirm_password_equipment/:id', to: 'users#confirm_password_equipment', as: 'confirm_password_equipment'
end

app/views/layouts/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0">
      <%=link_to root_path do%>
        <%= image_tag("logo.png", alt: "Logo", width: "50", height: "50", class: "d-inline-block align-text-center") %>
      <%end%>
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to "Clientes",  clients_path, class: "nav-link" , style:"color:#{'#f0438c 'if current_page?(clients_path) }"%>
        </li>
        <%if current_user.admin%>
          <li class="nav-item">
            <%= link_to "Personal",  users_path, class: "nav-link" , style:"color:#{'#f0438c 'if current_page?(users_path) }"%>
          </li>
        <%end%>
        <li class="nav-item">
                    <%= link_to "Aparatos",  equipment_index_path, class: "nav-link" , style:"color:#{'#f0438c' if current_page?(equipment_index_path)|| current_page?(root_path) }"%>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete,
        class: "btn btn-outline-secondary"
      ) %>

    </div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-body-secondary">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

     <% if notice && !current_page?(new_user_session_path) %>
        <p class="alert alert-success"><%= notice %></p>
     <% end %>

     <% if alert && !current_page?(new_user_session_path) %>
             <p class="alert alert-danger"><%= alert %></p>
     <% end %>
     <%if user_signed_in?%>
    <%= render 'layouts/navbar'  %>
    <%end%>
    <%= yield %>
  </body>
</html>